package com.denfense.server.service;
import com.denfense.server.domain.User; import com.denfense.server.dto.battle.BattleSettlementDtos; import com.denfense.server.exception.*; import com.denfense.server.repository.*; import com.denfense.server.service.balance.BalanceVersionRegistry; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import java.time.*; import java.util.*; import java.util.concurrent.*; import static org.assertj.core.api.Assertions.*;
@SpringBootTest class BattleSettlementIntegrationTest {
 @Autowired BattleSettlementService service; @Autowired UserRepository users; @Autowired BattleSettlementRepository settlements; @Autowired BattlePlayerSettlementRepository playerSettlements; @Autowired BattleRewardClaimRepository rewardClaims; @Autowired BalanceVersionRegistry versions;
 @BeforeEach void cleanup(){rewardClaims.deleteAll();playerSettlements.deleteAll();settlements.deleteAll();users.deleteAll();}
 @Test void normalSettlementPersistsTwoPlayersAndEmptyRewards(){User a=user("battle-a"),b=user("battle-b");var out=service.settle(valid("req-1","session-1","hash-1",a,b));assertThat(out.status()).isEqualTo("ACCEPTED");assertThat(out.alreadyProcessed()).isFalse();assertThat(out.rewards()).isEmpty();assertThat(settlements.count()).isEqualTo(1);assertThat(playerSettlements.count()).isEqualTo(2);}
 @Test void requestIdHasPriorityAndIsIdempotent(){User a=user("idem-a"),b=user("idem-b");var r=valid("same","s1","h1",a,b);service.settle(r);assertThat(service.settle(r).alreadyProcessed()).isTrue();assertThatThrownBy(()->service.settle(valid("same","s2","h1",a,b))).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_REQUEST_CONFLICT));}
 @Test void invalidGoldAndParticipantsAreRejected(){User a=user("invalid-a"),b=user("invalid-b");assertThatThrownBy(()->service.settle(new BattleSettlementDtos.Request("bad","sbad",versions.getBalanceVersion(),versions.getContentHash(),"VICTORY",1,LocalDateTime.now().minusMinutes(1),LocalDateTime.now(),List.of(player(a,1,99),player(b,2,100)),List.of(monster(2)),"h"))).isInstanceOf(BusinessException.class);}
 @Test void invalidResultIsRejectedAsBusinessError(){User a=user("result-a"),b=user("result-b");var valid=valid("bad-result","result-session","result-hash",a,b);var invalid=new BattleSettlementDtos.Request(valid.requestId(),valid.battleSessionId(),valid.balanceVersion(),valid.contentHash(),"CLEARED",valid.finalWave(),valid.startedAt(),valid.finishedAt(),valid.players(),valid.monsterKills(),valid.summaryHash());assertThatThrownBy(()->service.settle(invalid)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_SUMMARY_INVALID));}
 @Test void finalWaveAboveCanonicalMaximumIsRejected(){User a=user("wave-a"),b=user("wave-b");var invalid=valid("wave-invalid","wave-session","wave-hash",a,b,"DEFEAT",81,"EARTH");assertThatThrownBy(()->service.settle(invalid)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_SUMMARY_INVALID));}
 @Test void unknownMapIdIsRejectedBeforeRewardClaim(){User a=user("map-a"),b=user("map-b");var invalid=valid("map-invalid","map-session","map-hash",a,b,"DEFEAT",70,"UNKNOWN_PLANET");assertThatThrownBy(()->service.settle(invalid)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_SUMMARY_INVALID));}
 @Test void concurrentSameRequestCreatesOneSettlement() throws Exception{User a=user("conc-a"),b=user("conc-b");var r=valid("conc","sc","hc",a,b);ExecutorService ex=Executors.newFixedThreadPool(2);CountDownLatch gate=new CountDownLatch(1);Callable<BattleSettlementDtos.Response> task=()->{gate.await();return service.settle(r);};Future<BattleSettlementDtos.Response>x=ex.submit(task),y=ex.submit(task);gate.countDown();var rx=x.get();var ry=y.get();ex.shutdown();assertThat(settlements.count()).isEqualTo(1);assertThat(playerSettlements.count()).isEqualTo(2);assertThat(rx.alreadyProcessed()^ry.alreadyProcessed()).isTrue();}
 @Test void wave70FailureAwardsReachedCheckpointsOnlyOnce(){User a=user("reward-a"),b=user("reward-b");var r=valid("reward-70","reward-session-70","reward-hash-70",a,b,"DEFEAT",70,"EARTH");var first=service.settle(r);var second=service.settle(r);assertThat(first.rewards()).extracting(BattleSettlementDtos.Reward::rewardType).contains("SETTLEMENT","CHECKPOINT");assertThat(second.alreadyProcessed()).isTrue();assertThat(rewardClaims.findByBattleSessionIdOrderByIdAsc("reward-session-70")).hasSize(16);assertThat(users.findByUsername("reward-a").orElseThrow().getDiamond()).isZero();}
 @Test void firstVictoryAtWave80AwardsPlanetDiamondAndReclearDoesNotDuplicate(){User a=user("first-a"),b=user("first-b");var r=valid("first-clear","first-session","first-hash",a,b,"VICTORY",80,"EARTH");var first=service.settle(r);assertThat(first.rewards()).extracting(BattleSettlementDtos.Reward::rewardType).contains("MAP_FIRST_CLEAR");int claimsAfterFirst=rewardClaims.findByBattleSessionIdOrderByIdAsc("first-session").size();var second=service.settle(r);assertThat(second.alreadyProcessed()).isTrue();assertThat(rewardClaims.findByBattleSessionIdOrderByIdAsc("first-session")).hasSize(claimsAfterFirst);assertThat(users.findByUsername("first-a").orElseThrow().getDiamond()).isEqualTo(8000);}
 @Test void abandonedPlayerReceivesNoPermanentReward(){User a=user("active-player"),b=user("abandoned-player");var activeId=a.getId();var r=valid("abandoned","abandoned-session","abandoned-hash",a,b,"DEFEAT",70,"EARTH",false,true);service.settle(r);assertThat(rewardClaims.findByBattleSessionIdOrderByIdAsc("abandoned-session")).allMatch(c->c.getUser().getId().equals(activeId));}
 private BattleSettlementDtos.Request valid(String req,String sid,String hash,User a,User b){var now=LocalDateTime.now();return new BattleSettlementDtos.Request(req,sid,versions.getBalanceVersion(),versions.getContentHash(),"DEFEAT",1,now.minusMinutes(1),now,List.of(player(a,1,100),player(b,2,100)),List.of(monster(2)),hash);}
 private BattleSettlementDtos.Request valid(String req,String sid,String hash,User a,User b,String result,int wave,String map){return valid(req,sid,hash,a,b,result,wave,map,false,false);}
 private BattleSettlementDtos.Request valid(String req,String sid,String hash,User a,User b,String result,int wave,String map,boolean abandonedA,boolean abandonedB){var now=LocalDateTime.now();return new BattleSettlementDtos.Request(req,sid,versions.getBalanceVersion(),versions.getContentHash(),result,wave,map,now.minusMinutes(1),now,List.of(player(a,1,100,abandonedA),player(b,2,100,abandonedB)),List.of(monster(2)),hash);}
 private BattleSettlementDtos.Player player(User u,int slot,int finalGold){return new BattleSettlementDtos.Player(u.getUsername(),slot,false,null,1,0,0,100,0,0,finalGold);}
 private BattleSettlementDtos.Player player(User u,int slot,int finalGold,boolean abandoned){return new BattleSettlementDtos.Player(u.getUsername(),slot,false,null,1,0,0,100,0,0,finalGold,abandoned);}
 private BattleSettlementDtos.Monster monster(int total){return new BattleSettlementDtos.Monster("NORMAL_MONSTER",total,0,20*total);}
 private User user(String n){return users.save(new User(n,"pw"));}
}
