package com.denfense.server.service;
import com.denfense.server.domain.User; import com.denfense.server.dto.battle.BattleSettlementDtos; import com.denfense.server.exception.*; import com.denfense.server.repository.*; import com.denfense.server.service.balance.BalanceVersionRegistry; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import java.time.*; import java.util.*; import java.util.concurrent.*; import static org.assertj.core.api.Assertions.*;
@SpringBootTest class BattleSettlementIntegrationTest {
 @Autowired BattleSettlementService service; @Autowired UserRepository users; @Autowired BattleSettlementRepository settlements; @Autowired BattlePlayerSettlementRepository playerSettlements; @Autowired BalanceVersionRegistry versions;
 @BeforeEach void cleanup(){playerSettlements.deleteAll();settlements.deleteAll();users.deleteAll();}
 @Test void normalSettlementPersistsTwoPlayersAndEmptyRewards(){User a=user("battle-a"),b=user("battle-b");var out=service.settle(valid("req-1","session-1","hash-1",a,b));assertThat(out.status()).isEqualTo("ACCEPTED");assertThat(out.alreadyProcessed()).isFalse();assertThat(out.rewards()).isEmpty();assertThat(settlements.count()).isEqualTo(1);assertThat(playerSettlements.count()).isEqualTo(2);}
 @Test void requestIdHasPriorityAndIsIdempotent(){User a=user("idem-a"),b=user("idem-b");var r=valid("same","s1","h1",a,b);service.settle(r);assertThat(service.settle(r).alreadyProcessed()).isTrue();assertThatThrownBy(()->service.settle(valid("same","s2","h1",a,b))).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_REQUEST_CONFLICT));}
 @Test void invalidGoldAndParticipantsAreRejected(){User a=user("invalid-a"),b=user("invalid-b");assertThatThrownBy(()->service.settle(new BattleSettlementDtos.Request("bad","sbad",versions.getBalanceVersion(),versions.getContentHash(),"VICTORY",1,LocalDateTime.now().minusMinutes(1),LocalDateTime.now(),List.of(player(a,1,99),player(b,2,100)),List.of(monster(2)),"h"))).isInstanceOf(BusinessException.class);}
 @Test void invalidResultIsRejectedAsBusinessError(){User a=user("result-a"),b=user("result-b");var valid=valid("bad-result","result-session","result-hash",a,b);var invalid=new BattleSettlementDtos.Request(valid.requestId(),valid.battleSessionId(),valid.balanceVersion(),valid.contentHash(),"CLEARED",valid.finalWave(),valid.startedAt(),valid.finishedAt(),valid.players(),valid.monsterKills(),valid.summaryHash());assertThatThrownBy(()->service.settle(invalid)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.getErrorCode()).isEqualTo(ErrorCode.BATTLE_SUMMARY_INVALID));}
 @Test void concurrentSameRequestCreatesOneSettlement() throws Exception{User a=user("conc-a"),b=user("conc-b");var r=valid("conc","sc","hc",a,b);ExecutorService ex=Executors.newFixedThreadPool(2);CountDownLatch gate=new CountDownLatch(1);Callable<BattleSettlementDtos.Response> task=()->{gate.await();return service.settle(r);};Future<BattleSettlementDtos.Response>x=ex.submit(task),y=ex.submit(task);gate.countDown();var rx=x.get();var ry=y.get();ex.shutdown();assertThat(settlements.count()).isEqualTo(1);assertThat(playerSettlements.count()).isEqualTo(2);assertThat(rx.alreadyProcessed()^ry.alreadyProcessed()).isTrue();}
 @Test void concurrentSameRequestDifferentSessionReturnsRequestConflict() throws Exception{User a=user("conc-conflict-a"),b=user("conc-conflict-b");var first=valid("same-request","session-a","hash-a",a,b);var second=valid("same-request","session-b","hash-b",a,b);ExecutorService ex=Executors.newFixedThreadPool(2);CountDownLatch gate=new CountDownLatch(1);Callable<Object> task=()->{gate.await();try{return service.settle(first);}catch(BusinessException e){return e;}};Callable<Object> other=()->{gate.await();try{return service.settle(second);}catch(BusinessException e){return e;}};Future<Object>x=ex.submit(task),y=ex.submit(other);gate.countDown();Object rx=x.get(),ry=y.get();ex.shutdown();assertThat(List.of(rx,ry).stream().filter(BattleSettlementDtos.Response.class::isInstance).count()).isEqualTo(1);assertThat(List.of(rx,ry).stream().filter(BusinessException.class::isInstance).map(BusinessException.class::cast).findFirst().orElseThrow().getErrorCode()).isEqualTo(ErrorCode.BATTLE_REQUEST_CONFLICT);assertThat(settlements.count()).isEqualTo(1);assertThat(playerSettlements.count()).isEqualTo(2);}
 private BattleSettlementDtos.Request valid(String req,String sid,String hash,User a,User b){var now=LocalDateTime.now();return new BattleSettlementDtos.Request(req,sid,versions.getBalanceVersion(),versions.getContentHash(),"VICTORY",1,now.minusMinutes(1),now,List.of(player(a,1,100),player(b,2,100)),List.of(monster(2)),hash);}
 private BattleSettlementDtos.Player player(User u,int slot,int finalGold){return new BattleSettlementDtos.Player(u.getUsername(),slot,false,null,1,0,0,100,0,0,finalGold);}
 private BattleSettlementDtos.Monster monster(int total){return new BattleSettlementDtos.Monster("NORMAL_MONSTER",total,0,20*total);}
 private User user(String n){return users.save(new User(n,"pw"));}
}
